# Generated by Django 2.0 on 2018-04-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='电影院名')),
                ('addr', models.CharField(max_length=128, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=255, null=True, verbose_name='评论内容')),
                ('up_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
                ('create_data', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='电影名')),
                ('period', models.CharField(max_length=32, verbose_name='电影时长')),
                ('img', models.CharField(max_length=32, verbose_name='电影图片')),
                ('info', models.TextField(blank=True, max_length=255, null=True, verbose_name='电影简介')),
                ('plot', models.TextField(blank=True, max_length=1024, null=True, verbose_name='电影剧情')),
                ('company', models.CharField(blank=True, max_length=32, null=True, verbose_name='发行公司')),
                ('score', models.CharField(blank=True, max_length=32, null=True, verbose_name='电影评分')),
                ('comment_num', models.IntegerField(blank=True, null=True, verbose_name='评分人数')),
                ('like_num', models.IntegerField(blank=True, null=True, verbose_name='想看人数')),
                ('other_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='更多片名')),
                ('release', models.DateField(blank=True, null=True, verbose_name='上映时间')),
            ],
        ),
        migrations.CreateModel(
            name='MovieField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=32, verbose_name='开始时间')),
                ('price', models.IntegerField(default=0, verbose_name='票价')),
                ('play_date', models.DateField(verbose_name='播放日期')),
                ('ballot', models.IntegerField(verbose_name='票数')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Cinema', verbose_name='电影院')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieDetail', verbose_name='电影')),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='电影类型')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.SmallIntegerField(choices=[(0, '微信'), (1, '支付宝')])),
                ('payment_number', models.CharField(blank=True, max_length=128, null=True, verbose_name='支付第3方订单号')),
                ('order_number', models.CharField(max_length=128, unique=True, verbose_name='订单号')),
                ('actual_amount', models.FloatField(verbose_name='实付金额')),
                ('status', models.SmallIntegerField(choices=[(0, '交易成功'), (1, '待支付'), (2, '退费申请中'), (3, '已退费'), (4, '主动取消'), (5, '超时取消')], verbose_name='状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='订单生成时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='付款时间')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='订单取消时间')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.FloatField(verbose_name='电影票原价')),
                ('seat_row', models.IntegerField(verbose_name='行')),
                ('seat_col', models.IntegerField(verbose_name='列')),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_period_display', models.CharField(max_length=32, verbose_name='有效期显示')),
                ('valid_period', models.PositiveIntegerField(verbose_name='有效期(days)')),
                ('moviefield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieField')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Order')),
            ],
        ),
        migrations.CreateModel(
            name='PlayRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, verbose_name='播放厅名')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Cinema', verbose_name='关联电影院')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('head_img', models.CharField(default='default.jpg', max_length=64, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='扮演者')),
                ('Actor', models.IntegerField(choices=[(1, '导演'), (2, '编剧'), (3, '演员')], verbose_name='职责')),
                ('role', models.CharField(blank=True, max_length=32, null=True, verbose_name='扮演角色')),
                ('act_img', models.CharField(blank=True, max_length=64, null=True, verbose_name='演员图片')),
                ('role_timg', models.CharField(blank=True, max_length=64, null=True, verbose_name='角色图片')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieDetail', verbose_name='关联电影')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.UserInfo'),
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='mtype',
            field=models.ManyToManyField(to='film.MovieType', verbose_name='电影类型'),
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieDetail', verbose_name='评论电影'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='film.Comment', verbose_name='父级评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.UserInfo', verbose_name='评论者'),
        ),
    ]
