# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.FileField(default='/media/uploads/default.jpg', upload_to='upload', verbose_name='头像'),
        ),
    ]
