# Generated by Django 2.0 on 2018-05-04 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20180427_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='down_count',
            field=models.IntegerField(default=0, verbose_name='踩'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_count',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='img',
            field=models.FileField(blank=True, default='/media/upload/default_film.jpg', null=True, upload_to='upload', verbose_name='电影图片'),
        ),
        migrations.AlterField(
            model_name='moviefield',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieDetail', verbose_name='影片'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, '微信'), (1, '支付宝')], verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.UserInfo', verbose_name='支付人'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='moviefield',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.MovieField', verbose_name='影片场次'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.Order', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='valid_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='有效期(days)'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='valid_period_display',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='有效期显示'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='head_img',
            field=models.FileField(blank=True, default='/media/upload/default.jpg', null=True, upload_to='upload', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.FileField(blank=True, default='/media/upload/default_film.jpg', null=True, upload_to='upload', verbose_name='扮演角色'),
        ),
    ]
