# Generated by Django 2.0 on 2018-05-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20180504_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='role_timg',
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='share_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='转发人数'),
        ),
        migrations.AddField(
            model_name='worker',
            name='role_img',
            field=models.FileField(blank=True, default='/media/upload/default.jpg', null=True, upload_to='upload', verbose_name='角色图片'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='comment_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='评分人数'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='like_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='想看人数'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='act_img',
            field=models.FileField(blank=True, default='/media/upload/default.jpg', null=True, upload_to='upload', verbose_name='演员图片'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='扮演角色'),
        ),
    ]
